//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenIPC_Config.Assets {
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance",
            "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.Equals(null, resourceMan))
                {
                    System.Resources.ResourceManager temp =
                        new System.Resources.ResourceManager("OpenIPC_Config.Assets.Resources",
                            typeof(Resources).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        public static string MSPOSDToolTip
        {
            get { return ResourceManager.GetString("MSPOSDToolTip", resourceCulture); }
        }

        public static string IPToolTip
        {
            get { return ResourceManager.GetString("IPToolTip", resourceCulture); }
        }

        public static string RestartWfbToolTip
        {
            get { return ResourceManager.GetString("RestartWfbToolTip", resourceCulture); }
        }

        public static string RestartMajesticToolTip
        {
            get { return ResourceManager.GetString("RestartMajesticToolTip", resourceCulture); }
        }

        public static string ScriptFilesBackupToolTip
        {
            get { return ResourceManager.GetString("ScriptFilesBackupToolTip", resourceCulture); }
        }

        public static string RecOffToolTip
        {
            get { return ResourceManager.GetString("RecOffToolTip", resourceCulture); }
        }

        public static string RecOnToolTip
        {
            get { return ResourceManager.GetString("RecOnToolTip", resourceCulture); }
        }

        public static string OnBoardRecToolTip
        {
            get { return ResourceManager.GetString("OnBoardRecToolTip", resourceCulture); }
        }

        public static string UploadINavFontsToolTip
        {
            get { return ResourceManager.GetString("UploadINavFontsToolTip", resourceCulture); }
        }
        
        public static string AddMavlinkExtraToolTip
        {
            get { return ResourceManager.GetString("AddMavlinkExtraToolTip", resourceCulture); }
        }
        
        public static string DisableUART0ToolTip
        {
            get { return ResourceManager.GetString("DisableUART0ToolTip", resourceCulture); }
        }
        public static string EnableUART0ToolTip
        {
            get { return ResourceManager.GetString("EnableUART0ToolTip", resourceCulture); }
        }
        
        public static string ResetCameraToolTip
        {
            get { return ResourceManager.GetString("ResetCameraToolTip", resourceCulture); }
        }
        
        public static string SensorBinBackupToolTip
        {
            get { return ResourceManager.GetString("SensorBinBackupToolTip", resourceCulture); }
            
        }
        
        public static string SensorDriverBackupToolTip
        {
            get { return ResourceManager.GetString("SensorDriverBackupToolTip", resourceCulture); }
        }
        
        public static string SensorDriverUpdateToolTip
        {
            get { return ResourceManager.GetString("SensorDriverUpdateToolTip", resourceCulture); }
        }
        
        public static string SensorBinUpdateToolTip
        {
            get { return ResourceManager.GetString("SensorBinUpdateToolTip", resourceCulture); }
        }
        
        public static string ScriptFilesRestoreToolTip
        {
            get { return ResourceManager.GetString("ScriptFilesRestoreToolTip", resourceCulture); }
        }
        
        public static string RecvDroneKeyToolTip
        {
            get { return ResourceManager.GetString("RecvDroneKeyToolTip", resourceCulture); }
        }
        
        public static string ScanIpToolTip
        {
            get { return ResourceManager.GetString("ScanIpToolTip", resourceCulture); }
        }
        
        public static string SendDroneKeyToolTip
        {
            get { return ResourceManager.GetString("SendDroneKeyToolTip", resourceCulture); }
        }
        
        public static string StepsTextBox
        {
            get { return ResourceManager.GetString("StepsTextBox", resourceCulture); }
        }

        public static string btnVRXMSPDisplayPort
        {
            get { return ResourceManager.GetString("btnVRXMSPDisplayPort", resourceCulture); }
        }
        
        public static string btnVRXMajestic
        {
            get { return ResourceManager.GetString("btnVRXMajestic", resourceCulture); }
        }
        
        public static string GenerateKeysToolTip
        {
            get { return ResourceManager.GetString("GenerateKeysToolTip", resourceCulture); }
        }

        public static string SendGsKeyToolTip
        {
            get { return ResourceManager.GetString("SendGsKeyToolTip", resourceCulture); }
        }
        public static string RecvGsKeyToolTip
        {
            get { return ResourceManager.GetString("RecvGsKeyToolTip", resourceCulture); }
        }
        public static string btnSaveAndRestartWfbText
        {
            get { return ResourceManager.GetString("btnSaveAndRestartWfbText", resourceCulture); }
        }
        
        public static string FpvEnabledToolTip
        {
            get { return ResourceManager.GetString("FpvEnabledToolTip", resourceCulture); }  
        }
        public static string FpvNoiseLevelToolTip
        {
            get { return ResourceManager.GetString("FpvNoiseLevelToolTip", resourceCulture); }  
        }
        public static string FpvRoiQpToolTip
        {
            get { return ResourceManager.GetString("FpvRoiQpToolTip", resourceCulture); }  
        }
        public static string FpvRefEnhanceToolTip
        {
            get { return ResourceManager.GetString("FpvRefEnhanceToolTip", resourceCulture); }
        }
        public static string FpvRefPredToolTip
        {
            get { return ResourceManager.GetString("FpvRefPredToolTip", resourceCulture); }
        }
        public static string FpvIntraLineToolTip
        {
            get { return ResourceManager.GetString("FpvIntraLineToolTip", resourceCulture); }
        }
        public static string FpvIntraQpToolTip
        {
            get { return ResourceManager.GetString("FpvIntraQpToolTip", resourceCulture); }
        }
        public static string FpvRoiRectToolTip
        {
            get { return ResourceManager.GetString("FpvRoiRectToolTip", resourceCulture); }
        }
        
        public static string UpdateCameraToolTip
        {
            get { return ResourceManager.GetString("UpdateCameraToolTip", resourceCulture); }
        }
        
        public static string LocalIpToolTip
        {
            get { return ResourceManager.GetString("LocalIpToolTip", resourceCulture); }
        }
        
        public static string Enable40MhzToolTip
        {
            get { return ResourceManager.GetString("Enable40MhzToolTip", resourceCulture); }
        }
        
        public static string UploadLatestVtxMenuToolTip
        {
            get { return ResourceManager.GetString("UploadLatestVtxMenuToolTip", resourceCulture); }
        }

        public static string SelectBandwithToolTip
        {
            get { return ResourceManager.GetString("SelectBandwithToolTip", resourceCulture); }
        }
        public static string SelectMCSIndexToolTip
        {
            get { return ResourceManager.GetString("SelectMCSIndexToolTip", resourceCulture); }
        }
        public static string SelectStbcToolTip
        {
            get { return ResourceManager.GetString("SelectStbcToolTip", resourceCulture); }
        }
        
        public static string SelectLdpcToolTip
        {
            get { return ResourceManager.GetString("SelectLdpcToolTip", resourceCulture); }
        }
        
        public static string SelectFecKToolTip
        {
            get { return ResourceManager.GetString("SelectFecKToolTip", resourceCulture); }
        }
        public static string SelectFecNToolTip
        {
            get { return ResourceManager.GetString("SelectFecNToolTip", resourceCulture); }
        }

        public static string Select58GHzFrequencyToolTip
        {
            get { return ResourceManager.GetString("Select58GHzFrequencyToolTip", resourceCulture); }
        }
        public static string Select58GHzPowerToolTip
        {
            get { return ResourceManager.GetString("Select58GHzPowerToolTip", resourceCulture); }
        }
        public static string Select24GHzFrequencyToolTip
        {
            get { return ResourceManager.GetString("Select24GHzFrequencyToolTip", resourceCulture); }
        }
        public static string Select24GHzPowerToolTip
        {
            get { return ResourceManager.GetString("Select24GHzPowerToolTip", resourceCulture); }
        }
        
        public static string DroneKeyActionsToolTip
        {
            get { return ResourceManager.GetString("DroneKeyActionsToolTip", resourceCulture); }
        }

        public static string DeviceChkSumToolTip
        {
            get { return ResourceManager.GetString("DeviceChkSumToolTip", resourceCulture); }
        }
        
        public static string PingStatusToolTip
        {
            get { return ResourceManager.GetString("PingStatusToolTip", resourceCulture); }
        }
        
        public static string TelemetryRouterToolTip
        {
            get { return ResourceManager.GetString("TelemetryRouterToolTip", resourceCulture); }
        }
        
        public static string MSPOSDExtraCameraToolTip
        {
            get { return ResourceManager.GetString("MSPOSDExtraCameraToolTip", resourceCulture); }
        }
        public static string MSPOSDExtraGSToolTip
        {
            get { return ResourceManager.GetString("MSPOSDExtraGSToolTip", resourceCulture); }
        }
        
        public static string MSPOSDExtraRemovalToolTip
        {
            get { return ResourceManager.GetString("MSPOSDExtraRemovalToolTip", resourceCulture); }
            
        }

    }
}
